### ISSUE TITLE
elasticsearch.js not added in Magento 1.7.0.2

### ISSUE THREAD

**Issue by kw-pr** [ctasca/magento-elasticsearch-module#18]
Any idea why elasticsearch.js is not added to page in Magento ce-1.7.0.2?

Should the .js file in another directory?

**Comment by ctasca** [comment]
It could be just the matter to copy layout.xml from base to your design package. What are your design configuration settings?

**Comment by kw-pr** [comment]
I found out the script was added but a missing ; stop it from working and damaged all following scripts. Added a change. Thanks a lot!
