### ISSUE TITLE
Missing modman file

### ISSUE THREAD

**Issue by klein0r** [ctasca/magento-elasticsearch-module#24]
Please create a modman file for this extension - this is required by several deployment tools out there

**Comment by klein0r** [comment]
```
app/code/community/Pocketphp/* app/code/community/Pocketphp/
app/design/frontend/base/default/layout/* app/design/frontend/base/default/layout/
app/design/frontend/base/default/template/* app/design/frontend/base/default/template/
app/etc/modules/* app/etc/modules/
app/locale/en_GB/* app/locale/en_GB/
app/locale/en_US/* app/locale/en_US/
js/* js/
```

**Comment by ctasca** [comment]
There is no need for modman file. Installation paths are bundled in composer.json (@see extra node). Do you have problems installing the module?

**Comment by klein0r** [comment]
I know that an installation is possible without a modman file, but our deployment tool needs a modman file (like many other out there). Event it is not required by some deployment tools, you should add it.

Most magento extensions on Github include a modman file, too.
